In [1]:
import sys
import os
os.chdir("../")

In [2]:
import pandas as pd
import numpy as np
import data
from tqdm.auto import tqdm
from preprocess_utils.last_clickout_indices import find as find_last_clickout_indices
tqdm.pandas()
from IPython.display import display
pd.options.display.max_columns = None

In [3]:
df = data.train_df('small')

In [4]:
df

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
1,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,3
2,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
3,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
4,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
5,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
6,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,5
7,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1
8,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
9,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1
10,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
11,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,2
12,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
13,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
14,02HGRBA06ODU,fa3a53156ae5c,1541030978,28,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,23
15,02HGRBA06ODU,fa3a53156ae5c,1541031009,29,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
16,02HGRBA06ODU,fa3a53156ae5c,1541031044,46,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,17
17,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
18,02HGRBA06ODU,fa3a53156ae5c,1541031115,65,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,18
19,02SRUT1NQYH1,3599a6f709eab,1541063851,33,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,33
20,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,1
21,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,1
22,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
23,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
24,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
25,03K8AXBL4BX2,ec139e10b9238,1541100314,5,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,2
26,03K8AXBL4BX2,ec139e10b9238,1541100322,6,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,1
27,03K8AXBL4BX2,ec139e10b9238,1541100652,7,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,1
28,03P4VFKK12UO,325fafb5fa450,1541107286,2,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN,2
29,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499981,UVZH6I27GOX3,edbe71673a3b4,1541062815,3,filter selection,House / Apartment,NZ,"Melbourne, Australia",mobile,House / Apartment|Serviced Apartment,NaN,NaN,1
499982,UVZH6I27GOX3,edbe71673a3b4,1541062954,4,clickout item,2892807,NZ,"Melbourne, Australia",mobile,House / Apartment|Serviced Apartment,2892807|3178484|3382096|4042972|4179838|469235...,103|125|284|145|275|253|107|194|143|97|319|235...,1
499983,V0HEM664D9B2,751043bd8fd70,1541104760,1,search for destination,"Campos do Jordão, Brazil",BR,"Campos do Jordão, Brazil",desktop,NaN,NaN,NaN,1
499984,V0HEM664D9B2,751043bd8fd70,1541104770,2,filter selection,Hostal (ES),BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499985,V0HEM664D9B2,751043bd8fd70,1541104770,3,filter selection,Hotel,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499986,V0HEM664D9B2,751043bd8fd70,1541104770,4,filter selection,Motel,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499987,V0HEM664D9B2,751043bd8fd70,1541104770,5,filter selection,Resort,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499988,V0HEM664D9B2,751043bd8fd70,1541104770,6,filter selection,3 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499989,V0HEM664D9B2,751043bd8fd70,1541104770,7,filter selection,4 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499990,V0HEM664D9B2,751043bd8fd70,1541104770,8,filter selection,5 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1
499991,V0HEM664D9B2,751043bd8fd70,1541104780,9,filter selection,Hostal (ES),BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499992,V0HEM664D9B2,751043bd8fd70,1541104780,10,filter selection,Hotel,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499993,V0HEM664D9B2,751043bd8fd70,1541104780,11,filter selection,Motel,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499994,V0HEM664D9B2,751043bd8fd70,1541104780,12,filter selection,Resort,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499995,V0HEM664D9B2,751043bd8fd70,1541104780,13,filter selection,5 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499996,V0HEM664D9B2,751043bd8fd70,1541104810,14,search for destination,"Natal, Brazil",BR,"Natal, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1
499997,V0HEM664D9B2,751043bd8fd70,1541104897,40,interaction item image,867621,BR,"Natal, Brazil",desktop,NaN,NaN,NaN,26
499998,V0HEM664D9B2,751043bd8fd70,1541105018,44,interaction item image,2272844,BR,"Natal, Brazil",desktop,NaN,NaN,NaN,4
499999,V0HEM664D9B2,751043bd8fd70,1541105024,45,clickout item,2272844,BR,"Natal, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),117545|104985|2097018|326906|3369338|1710829|3...,97|90|51|98|42|54|52|63|79|76|45|45|73|52|44|3...,1
500000,V1JJ0GBFN7N5,a740bafb79df8,1541109778,1,search for destination,"Rome, Italy",SE,"Rome, Italy",mobile,NaN,NaN,NaN,1
500001,V1JJ0GBFN7N5,a740bafb79df8,1541109793,2,search for destination,"Solna, Sweden",SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1
500002,V1JJ0GBFN7N5,a740bafb79df8,1541109812,3,change of sort order,interaction sort button,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1
500003,V1JJ0GBFN7N5,a740bafb79df8,1541109822,4,change of sort order,price and recommended,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1
500004,V1JJ0GBFN7N5,a740bafb79df8,1541109822,5,filter selection,Best Value,SE,"Solna, Sweden",mobile,Best Value,NaN,NaN,1
500005,V1JJ0GBFN7N5,a740bafb79df8,1541109832,7,interaction item image,41401,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,2
500006,V1JJ0GBFN7N5,a740bafb79df8,1541109855,8,clickout item,41401,SE,"Solna, Sweden",mobile,Best Value,41401|153843|41248|41374|4776036|3499206|18364...,88|104|140|115|119|115|112|125|125|135|143,1
500007,V1JJ0GBFN7N5,a740bafb79df8,1541110345,9,search for destination,"Prague, Czech Republic",SE,"Prague, Czech Republic",mobile,NaN,NaN,NaN,1
500008,V1JJ0GBFN7N5,a740bafb79df8,1541110365,10,search for destination,"Solna, Sweden",SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1
500009,V1JJ0GBFN7N5,a740bafb79df8,1541110380,11,clickout item,41401,SE,"Solna, Sweden",mobile,NaN,41248|41401|153843|4776036|41374|3499206|78245...,140|88|104|119|115|115|135|143|125|125|112,1
500010,V1JJ0GBFN7N5,a740bafb79df8,1541110420,12,clickout item,41401,SE,"Solna, Sweden",mobile,NaN,41248|41401|153843|4776036|41374|3499206|78245...,140|88|104|119|115|115|135|143|125|125|112,1

In [5]:
last_clickout_idxs = find_last_clickout_indices(df)

HBox(children=(IntProgress(value=0, max=121122), HTML(value='')))

In [8]:
clickout_rows = df.loc[last_clickout_idxs, ['user_id','session_id','impressions']]
clickout_rows['impressions_count'] = clickout_rows.impressions.str.split('|').str.len()
clickout_rows = clickout_rows.drop('impressions', axis=1)

In [9]:
clickout_rows

             user_id     session_id  impressions_count
9       00RL8Z82B2Z1  aff3928535f48                 25
21      02SRUT1NQYH1  3599a6f709eab                 25
27      03K8AXBL4BX2  ec139e10b9238                 25
45      03P4VFKK12UO  325fafb5fa450                 25
48      0473FZ8UNXRS  bcc452f3350eb                 25
49      066TUPQWUEV5  7157899be2839                 25
51      06S61EKCW1JY  22b9deb2da8f7                 25
57      06SZHKMYOOI8  4c6062d7cefe4                 25
59      098CQXLJZ868  489f31ee6fca9                 25
62      09L0Y03JYTAC  91de23da01b00                 25
65      0FXZGX34RQMS  dbe408c81daf3                 25
66      0FZ7FKT6CB3D  698c0975e6ffe                 25
69      0IVOT7X0FJWE  554392be66854                  4
75      0K009FGORI30  b1eabf1f2e155                 25
77      0KCQVHPEIWT0  e665b2c1e8040                 25
102     0L2TX0JNYVQ6  06e7c29170946                 25
104     0LEN9Z40SUSJ  ae1026cd27f7e                 12
113     0LPWXP7ZIW88  3737c2c0740b5                 25
133     0NA8E4AD2VY7  336d9a46b826f                 25
135     0NN8D1GWBW1F  84316dcbfb8e3                 25
153     0O1CTEP95YKQ  af793494b5f84                 25
158     0P3WZY097PQI  2423aea8cde50                 25
203     0Q3605EUBZG3  641a409c90fac                 25
205     0RH6DTZGIKY8  a4927e71aa80e                 25
211     0S2J3RLMF1LO  571988c5366eb                 25
240     0SO132S6MH3O  7ddbbad580025                 25
245     0SVH5QYX372P  9eb4da70d5ccd                 25
251     0T819ODEIRA4  7643893620070                 16
252     0VNR91BTRLCP  0c086494b8b9b                 25
253     0VOL2T63B8FS  6d809cf3198b1                 25
...              ...            ...                ...
499765  S4D78FQEWU68  85029d7d3ec94                 25
499771  S65K6XJ195R0  8dd8886cebf88                 25
499774  SE9Z2J774QM3  6407d47bd15de                 25
499778  SW3ZJK3C3CQH  5f43ef7885de1                 24
499784  SXDDGC5CV1BJ  41a3ee7641c0d                 25
499813  SZDSUCKX5S4P  dea04ec6ff4ff                  5
499817  T3V239LJS7IR  52118f03002ee                 25
499823  T40DRKR38GV1  eb08ecbe6acfa                 11
499825  T5F4UGXNK7C6  98828a21a580e                 25
499832  T733H7CCY2MR  54596fd0b295a                 25
499845  TBXAXVPD1MN0  329bddfb7676c                 15
499871  TD3R9QLKS40K  a25868dcc768e                 25
499876  TK79E358HL60  a81d4bb971704                 25
499883  TKO86SO514Z1  e38fae897c75a                 25
499894  TOYF9K05F6I3  893c8aa03458e                 25
499896  TUZDD663WT99  ce50c25d74007                 25
499899  TX59JR4Z5D7R  95a46f449fcd8                 25
499904  TXTROCY2AM21  1e441b97b8fea                 25
499915  U06OFS0L7KYR  8913c195a3e01                 11
499922  U1OU22T0JLCA  d0edb6f053bd8                 25
499945  U523N1WC09JG  108233d35c554                 25
499950  U8562BBCOC86  e5620e86de34b                 20
499958  UBVNK4CXCTKY  6cab3916f550e                 25
499964  UC9FR6KP8H7K  2dbe2941b66d4                 25
499970  UE6NBAR9MFXL  d06914f08de88                 25
499975  UKNHVDSTPZ10  d1360ca318870                 25
499977  US0VDHYTI6KM  feadf9a6e9117                 13
499982  UVZH6I27GOX3  edbe71673a3b4                 25
499999  V0HEM664D9B2  751043bd8fd70                 25
500010  V1JJ0GBFN7N5  a740bafb79df8                 11

[63129 rows x 3 columns]

In [10]:
clickout_rows.impressions_count.values

array([25, 25, 25, ..., 25, 25, 11])

In [11]:
one_hot_counts = np.zeros((clickout_rows.shape[0],25), dtype=np.int8)
for i,c in enumerate(clickout_rows.impressions_count.values):
    one_hot_counts[i, 0:c] = 1

In [12]:
one_hot_counts

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int8)

In [13]:
for i in range(25):
    clickout_rows['impr_c{}'.format(i)] = one_hot_counts[:,i]

In [14]:
clickout_rows

,user_id,session_id,impressions_count,impr_c0,impr_c1,impr_c2,impr_c3,impr_c4,impr_c5,impr_c6,impr_c7,impr_c8,impr_c9,impr_c10,impr_c11,impr_c12,impr_c13,impr_c14,impr_c15,impr_c16,impr_c17,impr_c18,impr_c19,impr_c20,impr_c21,impr_c22,impr_c23,impr_c24
9,00RL8Z82B2Z1,aff3928535f48,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
21,02SRUT1NQYH1,3599a6f709eab,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
27,03K8AXBL4BX2,ec139e10b9238,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
45,03P4VFKK12UO,325fafb5fa450,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
48,0473FZ8UNXRS,bcc452f3350eb,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
49,066TUPQWUEV5,7157899be2839,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
51,06S61EKCW1JY,22b9deb2da8f7,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
57,06SZHKMYOOI8,4c6062d7cefe4,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
59,098CQXLJZ868,489f31ee6fca9,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
62,09L0Y03JYTAC,91de23da01b00,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
65,0FXZGX34RQMS,dbe408c81daf3,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
66,0FZ7FKT6CB3D,698c0975e6ffe,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
69,0IVOT7X0FJWE,554392be66854,4,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75,0K009FGORI30,b1eabf1f2e155,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
77,0KCQVHPEIWT0,e665b2c1e8040,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
102,0L2TX0JNYVQ6,06e7c29170946,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
104,0LEN9Z40SUSJ,ae1026cd27f7e,12,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
113,0LPWXP7ZIW88,3737c2c0740b5,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
133,0NA8E4AD2VY7,336d9a46b826f,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
135,0NN8D1GWBW1F,84316dcbfb8e3,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
153,0O1CTEP95YKQ,af793494b5f84,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
158,0P3WZY097PQI,2423aea8cde50,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
203,0Q3605EUBZG3,641a409c90fac,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
205,0RH6DTZGIKY8,a4927e71aa80e,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
211,0S2J3RLMF1LO,571988c5366eb,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
240,0SO132S6MH3O,7ddbbad580025,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
245,0SVH5QYX372P,9eb4da70d5ccd,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
251,0T819ODEIRA4,7643893620070,16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
252,0VNR91BTRLCP,0c086494b8b9b,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
253,0VOL2T63B8FS,6d809cf3198b1,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499765,S4D78FQEWU68,85029d7d3ec94,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499771,S65K6XJ195R0,8dd8886cebf88,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499774,SE9Z2J774QM3,6407d47bd15de,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499778,SW3ZJK3C3CQH,5f43ef7885de1,24,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
499784,SXDDGC5CV1BJ,41a3ee7641c0d,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499813,SZDSUCKX5S4P,dea04ec6ff4ff,5,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
499817,T3V239LJS7IR,52118f03002ee,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499823,T40DRKR38GV1,eb08ecbe6acfa,11,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
499825,T5F4UGXNK7C6,98828a21a580e,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499832,T733H7CCY2MR,54596fd0b295a,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499845,TBXAXVPD1MN0,329bddfb7676c,15,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
499871,TD3R9QLKS40K,a25868dcc768e,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499876,TK79E358HL60,a81d4bb971704,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499883,TKO86SO514Z1,e38fae897c75a,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499894,TOYF9K05F6I3,893c8aa03458e,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499896,TUZDD663WT99,ce50c25d74007,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499899,TX59JR4Z5D7R,95a46f449fcd8,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499904,TXTROCY2AM21,1e441b97b8fea,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499915,U06OFS0L7KYR,8913c195a3e01,11,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
499922,U1OU22T0JLCA,d0edb6f053bd8,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499945,U523N1WC09JG,108233d35c554,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499950,U8562BBCOC86,e5620e86de34b,20,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
499958,UBVNK4CXCTKY,6cab3916f550e,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499964,UC9FR6KP8H7K,2dbe2941b66d4,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499970,UE6NBAR9MFXL,d06914f08de88,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499975,UKNHVDSTPZ10,d1360ca318870,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499977,US0VDHYTI6KM,feadf9a6e9117,13,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
499982,UVZH6I27GOX3,edbe71673a3b4,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499999,V0HEM664D9B2,751043bd8fd70,25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
500010,V1JJ0GBFN7N5,a740bafb79df8,11,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
from extract_features.sessions_impressions_count import SessionsImpressionsCount
f = SessionsImpressionsCount()

In [5]:
f.join_to(df, one_hot=False)

sessions_impressions_count feature read

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence,impr_c0,impr_c1,impr_c2,impr_c3,impr_c4,impr_c5,impr_c6,impr_c7,impr_c8,impr_c9,impr_c10,impr_c11,impr_c12,impr_c13,impr_c14,impr_c15,impr_c16,impr_c17,impr_c18,impr_c19,impr_c20,impr_c21,impr_c22,impr_c23,impr_c24
index,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
7,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
8,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
9,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
10,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,02HGRBA06ODU,fa3a53156ae5c,1541030978,28,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,02HGRBA06ODU,fa3a53156ae5c,1541031009,29,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,02HGRBA06ODU,fa3a53156ae5c,1541031044,46,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,02HGRBA06ODU,fa3a53156ae5c,1541031115,65,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,02SRUT1NQYH1,3599a6f709eab,1541063851,33,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,33,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
20,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
21,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
22,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
23,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
24,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
25,03K8AXBL4BX2,ec139e10b9238,1541100314,5,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
26,03K8AXBL4BX2,ec139e10b9238,1541100322,6,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
27,03K8AXBL4BX2,ec139e10b9238,1541100652,7,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
28,03P4VFKK12UO,325fafb5fa450,1541107286,2,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
29,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499981,UVZH6I27GOX3,edbe71673a3b4,1541062815,3,filter selection,House / Apartment,NZ,"Melbourne, Australia",mobile,House / Apartment|Serviced Apartment,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499982,UVZH6I27GOX3,edbe71673a3b4,1541062954,4,clickout item,2892807,NZ,"Melbourne, Australia",mobile,House / Apartment|Serviced Apartment,2892807|3178484|3382096|4042972|4179838|469235...,103|125|284|145|275|253|107|194|143|97|319|235...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499983,V0HEM664D9B2,751043bd8fd70,1541104760,1,search for destination,"Campos do Jordão, Brazil",BR,"Campos do Jordão, Brazil",desktop,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499984,V0HEM664D9B2,751043bd8fd70,1541104770,2,filter selection,Hostal (ES),BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499985,V0HEM664D9B2,751043bd8fd70,1541104770,3,filter selection,Hotel,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499986,V0HEM664D9B2,751043bd8fd70,1541104770,4,filter selection,Motel,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499987,V0HEM664D9B2,751043bd8fd70,1541104770,5,filter selection,Resort,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499988,V0HEM664D9B2,751043bd8fd70,1541104770,6,filter selection,3 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499989,V0HEM664D9B2,751043bd8fd70,1541104770,7,filter selection,4 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499990,V0HEM664D9B2,751043bd8fd70,1541104770,8,filter selection,5 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499991,V0HEM664D9B2,751043bd8fd70,1541104780,9,filter selection,Hostal (ES),BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499992,V0HEM664D9B2,751043bd8fd70,1541104780,10,filter selection,Hotel,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499993,V0HEM664D9B2,751043bd8fd70,1541104780,11,filter selection,Motel,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499994,V0HEM664D9B2,751043bd8fd70,1541104780,12,filter selection,Resort,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499995,V0HEM664D9B2,751043bd8fd70,1541104780,13,filter selection,5 Star,BR,"Campos do Jordão, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499996,V0HEM664D9B2,751043bd8fd70,1541104810,14,search for destination,"Natal, Brazil",BR,"Natal, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499997,V0HEM664D9B2,751043bd8fd70,1541104897,40,interaction item image,867621,BR,"Natal, Brazil",desktop,NaN,NaN,NaN,26,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499998,V0HEM664D9B2,751043bd8fd70,1541105018,44,interaction item image,2272844,BR,"Natal, Brazil",desktop,NaN,NaN,NaN,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
499999,V0HEM664D9B2,751043bd8fd70,1541105024,45,clickout item,2272844,BR,"Natal, Brazil",desktop,5 Star|Hotel|Motel|Resort|Hostal (ES),117545|104985|2097018|326906|3369338|1710829|3...,97|90|51|98|42|54|52|63|79|76|45|45|73|52|44|3...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
500000,V1JJ0GBFN7N5,a740bafb79df8,1541109778,1,search for destination,"Rome, Italy",SE,"Rome, Italy",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500001,V1JJ0GBFN7N5,a740bafb79df8,1541109793,2,search for destination,"Solna, Sweden",SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500002,V1JJ0GBFN7N5,a740bafb79df8,1541109812,3,change of sort order,interaction sort button,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500003,V1JJ0GBFN7N5,a740bafb79df8,1541109822,4,change of sort order,price and recommended,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500004,V1JJ0GBFN7N5,a740bafb79df8,1541109822,5,filter selection,Best Value,SE,"Solna, Sweden",mobile,Best Value,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500005,V1JJ0GBFN7N5,a740bafb79df8,1541109832,7,interaction item image,41401,SE,"Solna, Sweden",mobile,NaN,NaN,NaN,2,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500006,V1JJ0GBFN7N5,a740bafb79df8,1541109855,8,clickout item,41401,SE,"Solna, Sweden",mobile,Best Value,41401|153843|41248|41374|4776036|3499206|18364...,88|104|140|115|119|115|112|125|125|135|143,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500007,V1JJ0GBFN7N5,a740bafb79df8,1541110345,9,search for destination,"Prague, Czech Republic",SE,"Prague, Czech Republic",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500008,V1JJ0GBFN7N5,a740bafb79df8,1541110365,10,search for destination,"Solna, Sweden",SE,"Solna, Sweden",mobile,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500009,V1JJ0GBFN7N5,a740bafb79df8,1541110380,11,clickout item,41401,SE,"Solna, Sweden",mobile,NaN,41248|41401|153843|4776036|41374|3499206|78245...,140|88|104|119|115|115|135|143|125|125|112,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
500010,V1JJ0GBFN7N5,a740bafb79df8,1541110420,12,clickout item,41401,SE,"Solna, Sweden",mobile,NaN,41248|41401|153843|4776036|41374|3499206|78245...,140|88|104|119|115|115|135|143|125|125|112,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [6]:
_.dtypes

user_id            object
session_id         object
timestamp           int64
step                int64
action_type        object
reference          object
platform           object
city               object
device             object
current_filters    object
impressions        object
prices             object
frequence           int64
impr_c0              int8
impr_c1              int8
impr_c2              int8
impr_c3              int8
impr_c4              int8
impr_c5              int8
impr_c6              int8
impr_c7              int8
impr_c8              int8
impr_c9              int8
impr_c10             int8
impr_c11             int8
impr_c12             int8
impr_c13             int8
impr_c14             int8
impr_c15             int8
impr_c16             int8
impr_c17             int8
impr_c18             int8
impr_c19             int8
impr_c20             int8
impr_c21             int8
impr_c22             int8
impr_c23             int8
impr_c24             int8
dtype: object

In [3]:
len(pd.read_csv('dataset/original/train.csv'))

15932992

In [4]:
len(data.train_df('local'))+len(data.test_df('local'))

/Users/federico/miniconda3/envs/recsys/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

Loading local test_df, it will take a while..

5232281

In [5]:
len(data.target_indices('local'))

153135

In [6]:
t1 = data.target_indices('local')

In [10]:
t2 = np.load('/Users/federico/Downloads/target_indices.npy')

In [11]:
set(t2).difference(set(t1))

{1874681,
 2591445,
 2598458,
 2746932,
 3565502,
 3964682,
 4198224,
 4687408,
 6258912,
 6335412,
 8064442,
 8540991,
 8971054,
 10252156,
 11238685,
 11487554,
 13057976,
 13637151,
 14572320,
 15353095}

In [12]:
len(t1)

153135

In [13]:
len(t2)

153136

In [14]:
data.train_df('local').loc[1874679:1874685]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence
1874679,GW6AGQ6BUKHX,9d9ac76a12cd5,1541380637,8,clickout item,4295908,BR,"São Roque, Brazil",mobile,NaN,4295908,47,1
1874680,GWRS3T865R8S,8eee8e386497c,1541400578,1,clickout item,98790,NZ,"Auckland, New Zealand",mobile,NaN,98790|120992|98817|349496|98808|98791|98789|96...,175|212|268|148|209|221|181|209|187|262|130|20...,1
1874681,GXE3E1B45B0I,3e6beef1892af,1541451599,1,clickout item,4954850,PT,"Ferreira do Zêzere, Portugal",mobile,NaN,4954850|607551|115106|3505086|3498524|1028138|...,64|80|69|50|45|44|50|35|50|40|40|40|60|49|35|7...,1
1874682,H35W08E5S30D,423a0d2e26ace,1541399859,1,search for poi,Old town of Heidelberg,DE,"Heidelberg, Germany",desktop,NaN,NaN,NaN,1
1874683,H35W08E5S30D,423a0d2e26ace,1541399878,2,filter selection,Breakfast Included,DE,"Heidelberg, Germany",desktop,Breakfast Included,NaN,NaN,1
1874684,H35W08E5S30D,423a0d2e26ace,1541399945,3,filter selection,Hotel,DE,"Heidelberg, Germany",desktop,Breakfast Included|Hotel,NaN,NaN,1
1874685,H35W08E5S30D,423a0d2e26ace,1541400179,4,search for destination,"Heidelberg, Germany",DE,"Heidelberg, Germany",desktop,Breakfast Included|Hotel|Focus on Distance,NaN,NaN,1

In [15]:
data.target_indices('full')

array([5232286, 5232288, 5232290, ..., 6694927, 6694932, 6694933])

In [16]:
15932998-5232286

10700712

In [17]:
19707168-6694933

13012235