In [1]:
import sys
import os
os.chdir("../")

In [2]:
import numpy as np
import pandas as pd
import data
from tqdm.auto import tqdm
tqdm.pandas()
from IPython.display import display
pd.options.display.max_columns = None

In [3]:
train_df = data.train_df('small')

In [4]:
train_df.head(30)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
1,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,3
2,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
3,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
4,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
5,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
6,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,5
7,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1
8,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1
9,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1
10,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
11,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,2
12,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
13,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
14,02HGRBA06ODU,fa3a53156ae5c,1541030978,28,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,23
15,02HGRBA06ODU,fa3a53156ae5c,1541031009,29,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
16,02HGRBA06ODU,fa3a53156ae5c,1541031044,46,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,17
17,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1
18,02HGRBA06ODU,fa3a53156ae5c,1541031115,65,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,18
19,02SRUT1NQYH1,3599a6f709eab,1541063851,33,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,33
20,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,1
21,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,1
22,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
23,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
24,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1
25,03K8AXBL4BX2,ec139e10b9238,1541100314,5,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,2
26,03K8AXBL4BX2,ec139e10b9238,1541100652,7,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,2
27,03P4VFKK12UO,325fafb5fa450,1541107286,2,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN,2
28,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN,1
29,03P4VFKK12UO,325fafb5fa450,1541107366,4,filter selection,Hostal (ES),US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN,1

In [10]:
train_df = train_df.sort_index()

In [11]:
clickout_rows = train_df[['user_id','session_id','action_type','prices']][train_df.action_type == 'clickout item']
clickout_rows['avg_price'] = clickout_rows.prices.str.split('|').apply(lambda x: np.mean(list(map(int,x))))
#clickout_rows['price_list'] = clickout_rows.prices.str.split('|')

rows = train_df[['user_id','session_id','reference']][train_df.reference.str.isnumeric()]
rows['avg_price'] = 0.0

In [12]:
clickout_rows.head()

,user_id,session_id,action_type,prices,avg_price
7,00RL8Z82B2Z1,aff3928535f48,clickout item,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,115.76
9,00RL8Z82B2Z1,aff3928535f48,clickout item,162|25|150|143|101|49|118|131|18|100|101|143|5...,110.04
21,02SRUT1NQYH1,3599a6f709eab,clickout item,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,82.96
26,03K8AXBL4BX2,ec139e10b9238,clickout item,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,95.84
43,03P4VFKK12UO,325fafb5fa450,clickout item,178|104|110|94|57|96|46|61|48|35|50|38|59|44|5...,68.44

In [13]:
rows.head(30)

         user_id     session_id reference  avg_price
1   00RL8Z82B2Z1  aff3928535f48    666856        0.0
2   00RL8Z82B2Z1  aff3928535f48    109038        0.0
3   00RL8Z82B2Z1  aff3928535f48    666856        0.0
4   00RL8Z82B2Z1  aff3928535f48    109038        0.0
5   00RL8Z82B2Z1  aff3928535f48    666856        0.0
6   00RL8Z82B2Z1  aff3928535f48    109038        0.0
7   00RL8Z82B2Z1  aff3928535f48    109038        0.0
9   00RL8Z82B2Z1  aff3928535f48   1257342        0.0
10  02HGRBA06ODU  fa3a53156ae5c   3377332        0.0
11  02HGRBA06ODU  fa3a53156ae5c   3377332        0.0
12  02HGRBA06ODU  fa3a53156ae5c   3377332        0.0
13  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
14  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
15  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
16  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
17  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
18  02HGRBA06ODU  fa3a53156ae5c   3066244        0.0
19  02SRUT1NQYH1  3599a6f709eab   2795374        0.0
20  02SRUT1NQYH1  3599a6f709eab   2795374        0.0
21  02SRUT1NQYH1  3599a6f709eab   2795374        0.0
25  03K8AXBL4BX2  ec139e10b9238   1032816        0.0
26  03K8AXBL4BX2  ec139e10b9238   1032816        0.0
42  03P4VFKK12UO  325fafb5fa450     65685        0.0
43  03P4VFKK12UO  325fafb5fa450     65685        0.0
44  03P4VFKK12UO  325fafb5fa450   1320460        0.0
45  0473FZ8UNXRS  bcc452f3350eb    749441        0.0
46  0473FZ8UNXRS  bcc452f3350eb   1258184        0.0
47  0473FZ8UNXRS  bcc452f3350eb   3143258        0.0
48  066TUPQWUEV5  7157899be2839   2552514        0.0
49  066TUPQWUEV5  7157899be2839   2552514        0.0

In [14]:
j = 0
clickout_indices = clickout_rows.index.values
for idx,row in tqdm(rows.iterrows()):
    # find the next clickout index
    if idx >= clickout_indices[-1]:
        break
    while idx > clickout_indices[j]:
        j += 1
    next_clickout = clickout_rows.loc[clickout_indices[j]]

    # check if row and next_clickout are in the same session
    if row.user_id == next_clickout.user_id and row.session_id == next_clickout.session_id:
        try:
            rows.at[idx,'avg_price'] = next_clickout.avg_price
        except:
            pass

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [15]:
rows

             user_id     session_id reference   avg_price
1       00RL8Z82B2Z1  aff3928535f48    666856  115.760000
2       00RL8Z82B2Z1  aff3928535f48    109038  115.760000
3       00RL8Z82B2Z1  aff3928535f48    666856  115.760000
4       00RL8Z82B2Z1  aff3928535f48    109038  115.760000
5       00RL8Z82B2Z1  aff3928535f48    666856  115.760000
6       00RL8Z82B2Z1  aff3928535f48    109038  115.760000
7       00RL8Z82B2Z1  aff3928535f48    109038  115.760000
9       00RL8Z82B2Z1  aff3928535f48   1257342  110.040000
10      02HGRBA06ODU  fa3a53156ae5c   3377332    0.000000
11      02HGRBA06ODU  fa3a53156ae5c   3377332    0.000000
12      02HGRBA06ODU  fa3a53156ae5c   3377332    0.000000
13      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
14      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
15      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
16      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
17      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
18      02HGRBA06ODU  fa3a53156ae5c   3066244    0.000000
19      02SRUT1NQYH1  3599a6f709eab   2795374   82.960000
20      02SRUT1NQYH1  3599a6f709eab   2795374   82.960000
21      02SRUT1NQYH1  3599a6f709eab   2795374   82.960000
25      03K8AXBL4BX2  ec139e10b9238   1032816   95.840000
26      03K8AXBL4BX2  ec139e10b9238   1032816   95.840000
42      03P4VFKK12UO  325fafb5fa450     65685   68.440000
43      03P4VFKK12UO  325fafb5fa450     65685   68.440000
44      03P4VFKK12UO  325fafb5fa450   1320460   68.440000
45      0473FZ8UNXRS  bcc452f3350eb    749441  100.720000
46      0473FZ8UNXRS  bcc452f3350eb   1258184  100.720000
47      0473FZ8UNXRS  bcc452f3350eb   3143258  100.720000
48      066TUPQWUEV5  7157899be2839   2552514   80.280000
49      066TUPQWUEV5  7157899be2839   2552514    0.000000
...              ...            ...       ...         ...
99998   X5LCV1SW6B0G  6288f0e7db512   1314270   31.318182
99999   X5LCV1SW6B0G  6288f0e7db512   5165974   31.318182
100001  X5RBR58Z3M62  21ffead5b9c92   1364710  143.880000
100002  X5RBR58Z3M62  21ffead5b9c92   1320620  143.880000
100003  X5RBR58Z3M62  21ffead5b9c92     12618  143.880000
100004  X5RBR58Z3M62  21ffead5b9c92     12618  143.880000
100005  X5RBR58Z3M62  21ffead5b9c92    934069  143.880000
100006  X5RBR58Z3M62  21ffead5b9c92   2333066   73.760000
100007  X5RBR58Z3M62  21ffead5b9c92   1320620   73.760000
100008  X5RBR58Z3M62  21ffead5b9c92   2333066   73.760000
100009  X5RBR58Z3M62  21ffead5b9c92     12618   73.760000
100010  X5RBR58Z3M62  21ffead5b9c92   3842698   73.760000
100011  X5RBR58Z3M62  21ffead5b9c92     12618   73.760000
100012  X5RBR58Z3M62  21ffead5b9c92   3842698   73.760000
100013  X5RBR58Z3M62  21ffead5b9c92   3842698   73.760000
100014  X5RBR58Z3M62  21ffead5b9c92     12618  214.080000
100015  X5RBR58Z3M62  21ffead5b9c92   2333066  214.080000
100016  X5RBR58Z3M62  21ffead5b9c92   1320620  214.080000
100017  X5RBR58Z3M62  21ffead5b9c92   1364710  214.080000
100018  X5RBR58Z3M62  21ffead5b9c92     12618  214.080000
100019  X5RBR58Z3M62  21ffead5b9c92   2333066  214.080000
100020  X5RBR58Z3M62  21ffead5b9c92     12618  214.080000
100021  X5RBR58Z3M62  21ffead5b9c92   1364710  214.080000
100022  X5RBR58Z3M62  21ffead5b9c92     12618  214.080000
100023  X5RBR58Z3M62  21ffead5b9c92   1320620  214.080000
100024  X5RBR58Z3M62  21ffead5b9c92   2333066  214.080000
100025  X5RBR58Z3M62  21ffead5b9c92   1364710  214.080000
100026  X5RBR58Z3M62  21ffead5b9c92   1320620  214.080000
100027  X5RBR58Z3M62  21ffead5b9c92    934069    0.000000
100028  X5RBR58Z3M62  21ffead5b9c92    934069    0.000000

[55704 rows x 4 columns]

In [16]:
rows.dtypes

user_id        object
session_id     object
reference      object
avg_price     float64
dtype: object

In [5]:
from extract_features.average_price_in_next_clickout import AveragePriceInNextClickout
f = AveragePriceInNextClickout()

In [6]:
f.join_to(train_df)

/Users/federico/miniconda3/envs/recsys/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

average_price_in_next_clickout feature read

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence,avg_price
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,0.000000
1,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,3,115.760000
2,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,115.760000
3,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,115.760000
4,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,115.760000
5,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,115.760000
6,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,5,115.760000
7,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1,115.760000
8,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN,1,0.000000
9,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1,110.040000
10,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0.000000
11,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,2,0.000000
12,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0.000000
13,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0.000000
14,02HGRBA06ODU,fa3a53156ae5c,1541030978,28,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,23,0.000000
15,02HGRBA06ODU,fa3a53156ae5c,1541031009,29,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0.000000
16,02HGRBA06ODU,fa3a53156ae5c,1541031044,46,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,17,0.000000
17,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,1,0.000000
18,02HGRBA06ODU,fa3a53156ae5c,1541031115,65,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN,18,0.000000
19,02SRUT1NQYH1,3599a6f709eab,1541063851,33,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,33,82.960000
20,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN,1,82.960000
21,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,1,82.960000
22,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,0.000000
23,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,0.000000
24,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,1,0.000000
25,03K8AXBL4BX2,ec139e10b9238,1541100314,5,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN,2,95.840000
26,03K8AXBL4BX2,ec139e10b9238,1541100652,7,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,2,95.840000
27,03P4VFKK12UO,325fafb5fa450,1541107286,2,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN,2,0.000000
28,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN,1,0.000000
29,03P4VFKK12UO,325fafb5fa450,1541107366,4,filter selection,Hostal (ES),US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99999,X5LCV1SW6B0G,6288f0e7db512,1541405514,27,clickout item,5165974,PL,"Bukowina Tatrzanska, Poland",desktop,NaN,988737|3936874|2673738|4779488|3557634|5540134...,23|27|27|19|23|32|63|75|18|84|25|25|23|16|28|2...,1,31.318182
100000,X5RBR58Z3M62,21ffead5b9c92,1541417747,1,search for destination,"Liverpool, United Kingdom",UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,0.000000
100001,X5RBR58Z3M62,21ffead5b9c92,1541417941,10,interaction item image,1364710,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,9,143.880000
100002,X5RBR58Z3M62,21ffead5b9c92,1541418014,43,interaction item image,1320620,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,33,143.880000
100003,X5RBR58Z3M62,21ffead5b9c92,1541418089,74,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,31,143.880000
100004,X5RBR58Z3M62,21ffead5b9c92,1541418089,75,interaction item info,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,143.880000
100005,X5RBR58Z3M62,21ffead5b9c92,1541418144,76,clickout item,934069,UK,"Liverpool, United Kingdom",desktop,NaN,152875|47374|2707162|18904|2826684|706646|9332...,185|69|102|109|284|192|129|180|170|77|92|134|1...,1,143.880000
100006,X5RBR58Z3M62,21ffead5b9c92,1541418502,99,interaction item image,2333066,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,23,73.760000
100007,X5RBR58Z3M62,21ffead5b9c92,1541418502,100,interaction item image,1320620,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,73.760000
100008,X5RBR58Z3M62,21ffead5b9c92,1541418504,101,interaction item image,2333066,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,73.760000
100009,X5RBR58Z3M62,21ffead5b9c92,1541418537,115,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,14,73.760000
100010,X5RBR58Z3M62,21ffead5b9c92,1541418537,117,interaction item image,3842698,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,2,73.760000
100011,X5RBR58Z3M62,21ffead5b9c92,1541418537,121,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,4,73.760000
100012,X5RBR58Z3M62,21ffead5b9c92,1541418547,135,interaction item image,3842698,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,14,73.760000
100013,X5RBR58Z3M62,21ffead5b9c92,1541418555,136,clickout item,3842698,UK,"Liverpool, United Kingdom",desktop,NaN,2530750|2707162|706646|18904|12618|3842698|470...,38|68|92|69|81|79|57|100|90|103|74|46|69|78|66...,1,73.760000
100014,X5RBR58Z3M62,21ffead5b9c92,1541418612,137,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100015,X5RBR58Z3M62,21ffead5b9c92,1541418614,138,interaction item image,2333066,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100016,X5RBR58Z3M62,21ffead5b9c92,1541418614,139,interaction item image,1320620,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100017,X5RBR58Z3M62,21ffead5b9c92,1541418614,140,interaction item image,1364710,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100018,X5RBR58Z3M62,21ffead5b9c92,1541418614,141,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100019,X5RBR58Z3M62,21ffead5b9c92,1541418615,142,interaction item image,2333066,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100020,X5RBR58Z3M62,21ffead5b9c92,1541418615,143,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100021,X5RBR58Z3M62,21ffead5b9c92,1541418615,144,interaction item image,1364710,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100022,X5RBR58Z3M62,21ffead5b9c92,1541418620,145,interaction item image,12618,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100023,X5RBR58Z3M62,21ffead5b9c92,1541418634,146,interaction item image,1320620,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100024,X5RBR58Z3M62,21ffead5b9c92,1541418634,147,interaction item image,2333066,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100025,X5RBR58Z3M62,21ffead5b9c92,1541418634,148,interaction item image,1364710,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,214.080000
100026,X5RBR58Z3M62,21ffead5b9c92,1541418732,161,interaction item image,1320620,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,13,214.080000
100027,X5RBR58Z3M62,21ffead5b9c92,1541418745,162,clickout item,934069,UK,"Liverpool, United Kingdom",desktop,NaN,18910|743096|47374|2826684|1364710|5206872|132...,200|86|101|284|102|106|413|166|184|164|133|200...,1,214.080000
100028,X5RBR58Z3M62,21ffead5b9c92,1541418767,163,interaction item deals,934069,UK,"Liverpool, United Kingdom",desktop,NaN,NaN,NaN,1,0.000000