In [1]:
import os
os.chdir('../')

In [2]:
import data
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from sklearn.preprocessing import MinMaxScaler
from tqdm.auto import tqdm

In [3]:
train_df = data.full_df()

caching df_full...

/Users/federico/miniconda3/envs/recsys/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

Done!

In [4]:
train_df.tail()

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence
6694929,ZZ39YE45SZIE,f5db4092ec9fc,1541551888,3,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN,2
6694930,ZZ39YE45SZIE,f5db4092ec9fc,1541551891,4,clickout item,2849116,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...,1
6694931,ZZ39YE45SZIE,f5db4092ec9fc,1541551899,5,interaction item image,2849116,HK,"Taitung City, Taiwan",mobile,NaN,NaN,NaN,1
6694932,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...,1
6694933,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...,1

## Count the numeric references

In [5]:
references = train_df[train_df.reference.str.isnumeric() == True].reference.values.astype('int')

In [6]:
references

array([ 666856,  109038,  666856, ..., 2849116, 2849116, 2849116])

In [9]:
cnt = Counter(references)

In [28]:
pop_df = pd.DataFrame(cnt.items(), columns=['reference','glob_popularity'])
pop_df = pop_df.sort_values('glob_popularity', ascending=False).reset_index(drop=True).reset_index()
pop_df['index'] = pop_df.index + 1
pop_df = pop_df.set_index('index')
pop_df

        reference  glob_popularity
index
1            8796             1899
2         9773310             1489
3            8561             1425
4            8621             1405
5            8589             1374
6         1811137             1347
7            8586             1330
8          100227             1307
9            8618             1252
10        1455251             1241
11         948643             1221
12        2784325             1177
13        1649739             1136
14        2053822             1135
15         499361             1043
16        3148916             1027
17           8588             1019
18        8805412             1012
19         496141             1001
20           8564              996
21           8551              972
22        3818266              961
23          34366              945
24        2165594              945
25         921237              918
26         104802              916
27           8640              909
28        3811810              904
29          42378              898
30         664366              885
...           ...              ...
394209    5152830                1
394210    6298376                1
394211   10952440                1
394212    9609176                1
394213    1104356                1
394214    3161992                1
394215    9739466                1
394216    9489672                1
394217    8755786                1
394218    6701810                1
394219    9382488                1
394220    2020113                1
394221    8227426                1
394222    1411572                1
394223    4041146                1
394224     364041                1
394225   10978596                1
394226    1411729                1
394227    1590361                1
394228    1175902                1
394229    1772843                1
394230      41761                1
394231    1839363                1
394232    9147556                1
394233    4425200                1
394234    2820098                1
394235      36331                1
394236    5173436                1
394237    2024619                1
394238     125990                1

[394238 rows x 2 columns]

In [29]:
pop_df.drop('glob_popularity', axis=1).to_csv('ref_embedding.csv')

In [9]:
len(cnt)

394238

In [30]:
cnt.most_common(100)

[(8796, 1899),
 (9773310, 1489),
 (8561, 1425),
 (8621, 1405),
 (8589, 1374),
 (1811137, 1347),
 (8586, 1330),
 (100227, 1307),
 (8618, 1252),
 (1455251, 1241),
 (948643, 1221),
 (2784325, 1177),
 (1649739, 1136),
 (2053822, 1135),
 (499361, 1043),
 (3148916, 1027),
 (8588, 1019),
 (8805412, 1012),
 (496141, 1001),
 (8564, 996),
 (8551, 972),
 (3818266, 961),
 (2165594, 945),
 (34366, 945),
 (921237, 918),
 (104802, 916),
 (8640, 909),
 (3811810, 904),
 (42378, 898),
 (664366, 885),
 (14243, 879),
 (8577, 848),
 (2759718, 842),
 (102080, 842),
 (100224, 842),
 (103452, 839),
 (67445, 837),
 (1321131, 835),
 (34506, 830),
 (352416, 810),
 (103600, 808),
 (2547593, 808),
 (3921330, 800),
 (1153426, 791),
 (894539, 788),
 (34429, 784),
 (44208, 778),
 (3248926, 776),
 (2450306, 772),
 (448986, 770),
 (6230236, 762),
 (4467826, 739),
 (43174, 739),
 (93683, 738),
 (3148414, 736),
 (42276, 731),
 (67361, 727),
 (32676, 727),
 (5763948, 717),
 (8568, 714),
 (503361, 703),
 (4638392, 701),
 (1063032, 696),
 (473691, 692),
 (8595, 692),
 (2884070, 672),
 (36455, 669),
 (1345387, 665),
 (2152342, 665),
 (34464, 664),
 (46985, 663),
 (106481, 661),
 (346866, 660),
 (2594544, 659),
 (109324, 653),
 (2326194, 652),
 (103557, 651),
 (2469404, 645),
 (1810141, 642),
 (8744, 639),
 (2517193, 630),
 (1473305, 626),
 (745041, 623),
 (962211, 622),
 (42996, 616),
 (103498, 613),
 (2128208, 611),
 (2195678, 609),
 (107154, 609),
 (5002942, 609),
 (1890753, 605),
 (46272, 603),
 (393591, 602),
 (6163642, 602),
 (61700, 597),
 (2106348, 597),
 (1127559, 597),
 (42793, 592),
 (1321090, 590),
 (95685, 588)]

## Count the impressions

In [48]:
impressions = list(train_df[train_df.action_type == 'clickout item'].impressions.str.split('|').values)

In [49]:
impressions = [int(item) for sublist in impressions for item in sublist]

In [50]:
impressions

[3400638,
 1253714,
 3367857,
 5100540,
 1088584,
 666916,
 54833,
 2922310,
 9711560,
 109038,
 666856,
 10077318,
 1431482,
 129343,
 6339822,
 6806806,
 1041528,
 109013,
 3909420,
 55088,
 3095758,
 109018,
 54885,
 1257342,
 2595006,
 55109,
 129343,
 54824,
 2297972,
 109014,
 1257342,
 1031578,
 109018,
 1332971,
 666916,
 54833,
 54885,
 2237222,
 10077318,
 1166793,
 9132132,
 1474297,
 3909420,
 6622154,
 55091,
 8444418,
 54804,
 2050977,
 666936,
 55088,
 2795374,
 5582964,
 1088390,
 2781070,
 1258068,
 1271962,
 3184892,
 148884,
 3528776,
 107183,
 5156744,
 107048,
 1907333,
 3370484,
 6003326,
 8436316,
 9025316,
 125181,
 3861490,
 131257,
 4415954,
 107162,
 3143352,
 6652864,
 8118684,
 12693,
 46363,
 81657,
 18448,
 47687,
 152913,
 18417,
 927627,
 4147572,
 819616,
 18380,
 47333,
 18425,
 1255377,
 4043482,
 1032816,
 18388,
 1216900,
 106471,
 106567,
 12667,
 84082,
 1152188,
 98737,
 47410,
 1306936,
 56482,
 2842358,
 6881276,
 65685,
 63259,
 65399,
 1320460,
 360566,
 376756,
 885381,
 60769,
 2141484,
 375876,
 829246,
 58909,
 360571,
 1298518,
 63542,
 71926,
 376076,
 57803,
 376181,
 1117192,
 359326,
 1306936,
 56482,
 2842358,
 6881276,
 65685,
 63259,
 65399,
 1320460,
 360566,
 376756,
 885381,
 60769,
 2141484,
 375876,
 829246,
 58909,
 360571,
 1298518,
 63542,
 71926,
 376076,
 57803,
 376181,
 1117192,
 359326,
 1258184,
 3866722,
 8929970,
 2315702,
 116619,
 1511641,
 111929,
 3223738,
 1288161,
 2870144,
 5788568,
 93911,
 94842,
 104163,
 159006,
 749441,
 955179,
 1670979,
 1890015,
 2073706,
 2081896,
 2162500,
 2625059,
 3143258,
 4926962,
 2349076,
 2552514,
 7159866,
 3898458,
 1846017,
 7250252,
 2828571,
 2685752,
 8775800,
 7721912,
 2019273,
 2674824,
 2675278,
 2677206,
 2754104,
 2754106,
 2756126,
 2759902,
 2881712,
 3245044,
 3245301,
 3245316,
 4704368,
 5117712,
 5942776,
 6721,
 6724,
 40109,
 147227,
 80983,
 6719,
 40718,
 1194054,
 624921,
 511646,
 1490687,
 32937,
 82021,
 81021,
 40872,
 2798980,
 160439,
 3916322,
 80862,
 110591,
 80907,
 970167,
 147226,
 40282,
 86878,
 22953,
 22951,
 22947,
 22949,
 8774118,
 45527,
 82900,
 22952,
 138929,
 2557176,
 138930,
 82901,
 108584,
 1685419,
 138928,
 898407,
 22954,
 82902,
 1240717,
 4970574,
 6471774,
 5433230,
 3219404,
 3768162,
 3186611,
 22953,
 22951,
 22947,
 22949,
 8774118,
 45527,
 82900,
 22952,
 138929,
 2557176,
 138930,
 82901,
 108584,
 1685419,
 138928,
 898407,
 22954,
 82902,
 1240717,
 4970574,
 6471774,
 5433230,
 3219404,
 3768162,
 3186611,
 129881,
 36161,
 36249,
 464421,
 302607,
 36401,
 302622,
 926841,
 302477,
 461661,
 36159,
 155275,
 300502,
 458386,
 302377,
 1867621,
 248817,
 1509639,
 2561050,
 291707,
 1557741,
 1997383,
 1557541,
 96347,
 1599007,
 8561,
 8564,
 8568,
 8586,
 8588,
 102080,
 8613,
 55677,
 57049,
 58492,
 1238070,
 1810141,
 72426,
 8618,
 893925,
 129571,
 8602,
 8578,
 8544,
 8576,
 8599,
 8543,
 8567,
 8619,
 8582,
 2603858,
 1765201,
 1844107,
 99445,
 99438,
 2219728,
 99439,
 3135583,
 2396864,
 99446,
 2527426,
 1572733,
 2529658,
 3842282,
 99448,
 8510198,
 3365566,
 1642853,
 2728330,
 2686097,
 2757598,
 489606,
 3176346,
 1258436,
 2277188,
 921237,
 147262,
 42194,
 9051714,
 42109,
 42125,
 3583264,
 100650,
 2524766,
 42102,
 147253,
 42198,
 107767,
 42134,
 82373,
 42313,
 100632,
 8435844,
 42309,
 42227,
 137704,
 8909410,
 2174748,
 100603,
 42089,
 2035675,
 4095738,
 4933410,
 9167996,
 104499,
 104710,
 104724,
 164677,
 960133,
 5816566,
 8740576,
 104938,
 1891457,
 104671,
 2454130,
 4343598,
 104771,
 397631,
 104986,
 479201,
 1501449,
 478216,
 104667,
 2627267,
 104599,
 522036,
 104770,
 104576,
 1689669,
 9172186,
 6816668,
 4497388,
 1827505,
 2066390,
 2729196,
 106415,
 3241854,
 478026,
 4138580,
 1948335,
 478911,
 1911027,
 478731,
 477866,
 2078560,
 2849878,
 2717643,
 6299940,
 991495,
 3193788,
 2078488,
 479041,
 655676,
 2003215,
 2802232,
 2733571,
 5477718,
 155374,
 155465,
 3549258,
 10091602,
 6508748,
 844336,
 4638538,
 3501450,
 390361,
 3501452,
 363046,
 2555968,
 5197174,
 4773608,
 3171165,
 3954788,
 6833196,
 5645106,
 475256,
 1627467,
 4871108,
 9033886,
 3549258,
 155465,
 155374,
 363046,
 3954788,
 4773608,
 3501452,
 10091602,
 2733571,
 5477718,
 6800422,
 2855981,
 3499270,
 3825178,
 6625240,
 6893402,
 5645106,
 1627467,
 4638538,
 9386776,
 3171165,
 4871108,
 2727688,
 6523164,
 2267026,
 2736998,
 9386776,
 7016734,
 2867638,
 797516,
 5677278,
 3954788,
 475131,
 385916,
 5702366,
 2855981,
 1891895,
 363046,
 6625240,
 3549258,
 3126684,
 1394008,
 6893402,
 363061,
 155989,
 6800422,
 4773608,
 3499270,
 155465,
 3145303,
 5109850,
 3505382,
 377811,
 155374,
 4849224,
 3501452,
 10091602,
 3367204,
 8143802,
 2733571,
 5477718,
 3136052,
 2267026,
 4638538,
 4454362,
 3825178,
 2727688,
 3899082,
 2738638,
 1627467,
 3171165,
 475206,
 3181886,
 475256,
 5645106,
 5109850,
 3505382,
 377811,
 155374,
 4849224,
 3501452,
 10091602,
 3367204,
 8143802,
 2733571,
 5477718,
 3136052,
 2267026,
 4638538,
 4454362,
 3825178,
 2727688,
 3899082,
 2738638,
 1627467,
 3171165,
 475206,
 3181886,
 475256,
 5645106,
 10091602,
 6625240,
 9386776,
 3954788,
 9776792,
 2802232,
 6893402,
 2855981,
 3501452,
 155374,
 155465,
 156621,
 363046,
 475101,
 1824477,
 2733571,
 2736998,
 3549258,
 4638538,
 5477718,
 8403088,
 8444298,
 7016734,
 1176048,
 4773608,
 47767,
 959737,
 3191226,
 1362528,
 1950827,
 1504481,
 2303554,
 1838303,
 1504415,
 2282346,
 3187638,
 7854780,
 43007,
 42365,
 42884,
 349051,
 489031,
 488961,
 1028438,
 3754668,
 1028442,
 9457620,
 1196746,
 3872766,
 42964,
 2038963,
 4018094,
 9603148,
 897983,
 9387652,
 2571851,
 2007837,
 4626178,
 349026,
 4174618,
 6869184,
 4012024,
 42365,
 42407,
 42884,
 42964,
 43007,
 349026,
 349051,
 489031,
 489171,
 897983,
 1141358,
 1972393,
 2007837,
 2030759,
 2038963,
 2123168,
 2561280,
 2564964,
 2571851,
 2636158,
 2896408,
 3429300,
 3478178,
 3484132,
 3872766,
 42365,
 42407,
 42884,
 42964,
 43007,
 349026,
 349051,
 489031,
 489171,
 897983,
 1141358,
 1972393,
 2007837,
 2030759,
 2038963,
 2123168,
 2561280,
 2564964,
 2571851,
 2636158,
 2896408,
 3429300,
 3478178,
 3484132,
 3872766,
 42365,
 42407,
 42884,
 42964,
 43007,
 349026,
 349051,
 489031,
 489171,
 897983,
 1141358,
 1972393,
 2007837,
 2030759,
 2038963,
 2123168,
 2561280,
 2564964,
 2571851,
 2636158,
 2896408,
 3429300,
 3478178,
 3484132,
 3872766,
 43007,
 42884,
 932627,
 3496252,
 488961,
 42365,
 43100,
 349051,
 741136,
 897983,
 127738,
 42964,
 8766024,
 2631244,
 1314827,
 2319440,
 2569442,
 9309368,
 373811,
 6696574,
 1815905,
 1772827,
 3484132,
 43141,
 1028442,
 1045290,
 3135752,
 1372961,
 1369024,
 3384308,
 1371070,
 1191128,
 320366,
 2589366,
 1373129,
 1091180,
 3404929,
 5813690,
 939106,
 940286,
 3183138,
 1370286,
 384511,
 5127144,
 2740100,
 939964,
 1327476,
 3961622,
 939114,
 1370246,
 1045290,
 3135752,
 1372961,
 1369024,
 3384308,
 1371070,
 1191128,
 320366,
 2589366,
 1373129,
 1091180,
 3404929,
 5813690,
 939106,
 940286,
 3183138,
 1370286,
 384511,
 5127144,
 2740100,
 939964,
 1327476,
 3961622,
 939114,
 1370246,
 9164598,
 1400686,
 2216204,
 2817576,
 4775794,
 5684276,
 5845180,
 5963262,
 7171090,
 7171192,
 8137972,
 8315816,
 8505876,
 9787844,
 10057298,
 7359812,
 8421086,
 9344376,
 7132982,
 7043076,
 4564186,
 9481878,
 5824184,
 6902620,
 2394112,
 69086,
 8533,
 925367,
 58949,
 61049,
 8581,
 8517,
 77520,
 8531,
 4169220,
 63051,
 397316,
 840726,
 2851635,
 1493341,
 8804492,
 62454,
 450176,
 102082,
 148954,
 8602,
 441851,
 63858,
 8516,
 8510248,
 69086,
 8533,
 925367,
 58949,
 61049,
 8581,
 8517,
 77520,
 8531,
 4169220,
 63051,
 397316,
 840726,
 2851635,
 1493341,
 8804492,
 62454,
 450176,
 102082,
 148954,
 8602,
 441851,
 63858,
 8516,
 8510248,
 69086,
 8533,
 925367,
 58949,
 61049,
 8581,
 8517,
 77520,
 8531,
 4169220,
 63051,
 397316,
 840726,
 2851635,
 1493341,
 8804492,
 62454,
 450176,
 102082,
 148954,
 8602,
 441851,
 63858,
 8516,
 8510248,
 8621,
 77124,
 8624,
 2851635,
 488501,
 1810141,
 72285,
 8589,
 8620,
 129571,
 8588,
 8572,
 8577,
 2793224,
 904927,
 102080,
 8518,
 72426,
 8563,
 57049,
 8599,
 32727,
 8568,
 8582,
 8586,
 8621,
 77124,
 8624,
 2851635,
 488501,
 1810141,
 72285,
 8589,
 8620,
 129571,
 8588,
 8572,
 8577,
 2793224,
 904927,
 102080,
 8518,
 72426,
 8563,
 57049,
 8599,
 32727,
 8568,
 8582,
 8586,
 8602,
 8568,
 8621,
 8561,
 57049,
 8564,
 8586,
 8577,
 8589,
 55677,
 77124,
 148957,
 893925,
 1217148,
 8588,
 2793224,
 8576,
 1238070,
 2282298,
 32727,
 8614,
 73555,
 567281,
 1094242,
 64376,
 2303306,
 4041114,
 5830856,
 111534,
 109353,
 5723646,
 1208722,
 1255025,
 1670475,
 1055330,
 655691,
 2284048,
 104681,
 104809,
 130772,
 5822734,
 1668389,
 1771225,
 2342182,
 104800,
 1329092,
 9719914,
 2627243,
 3249257,
 109332,
 5016850,
 2068758,
 1771981,
 2303306,
 2733700,
 3189448,
 5849680,
 1179630,
 1319947,
 1770143,
 925941,
 926343,
 8428074,
 109331,
 829671,
 3906960,
 4094062,
 5723646,
 3904508,
 5196406,
 2891934,
 6015920,
 2085246,
 5493194,
 104900,
 1236209,
 131152,
 1322948,
 7500,
 439106,
 7499,
 95072,
 95346,
 121982,
 ...]

In [51]:
cnt2 = Counter(impressions)

In [52]:
len(cnt2)

852890

## Feature

In [3]:
df = data.train_df('small')

In [7]:
d = df[(df.action_type == 'clickout item') & (df.reference.str.isnumeric() == True)] \
                    [['reference','frequence']].astype('int').groupby('reference').sum() \
                    .to_dict()['frequence']

In [8]:
d

{5003: 3,
 5004: 2,
 5014: 2,
 5017: 3,
 5021: 1,
 5022: 1,
 5023: 3,
 5040: 3,
 5041: 1,
 5042: 1,
 5049: 1,
 5053: 1,
 5055: 3,
 5072: 2,
 5073: 1,
 5075: 2,
 5082: 1,
 5094: 3,
 5097: 1,
 5102: 1,
 5116: 2,
 5122: 1,
 5124: 3,
 5131: 1,
 5136: 1,
 5148: 1,
 5150: 1,
 5154: 1,
 5166: 1,
 5168: 1,
 5172: 2,
 5185: 9,
 5192: 1,
 5193: 1,
 5196: 1,
 5198: 2,
 5200: 3,
 5202: 5,
 5205: 3,
 5209: 1,
 5212: 2,
 5213: 1,
 5215: 2,
 5217: 2,
 5222: 1,
 5228: 1,
 5232: 1,
 5234: 1,
 5250: 2,
 5253: 1,
 5261: 1,
 5269: 3,
 5273: 1,
 5277: 1,
 5281: 1,
 5282: 3,
 5283: 1,
 5295: 1,
 5301: 1,
 5321: 2,
 5327: 1,
 5341: 3,
 5348: 1,
 5350: 1,
 5363: 3,
 5365: 2,
 5368: 1,
 5369: 1,
 5372: 1,
 5373: 1,
 5374: 2,
 5375: 2,
 5380: 1,
 5382: 1,
 5383: 1,
 5401: 1,
 5403: 1,
 5412: 2,
 5415: 1,
 5416: 1,
 5417: 2,
 5420: 1,
 5422: 1,
 5435: 1,
 5439: 3,
 5456: 1,
 5470: 1,
 5483: 2,
 5490: 1,
 5500: 1,
 5507: 1,
 5527: 1,
 5531: 1,
 5535: 2,
 5537: 1,
 5541: 2,
 5542: 1,
 5543: 1,
 5544: 3,
 5547: 5,
 5549: 1,
 5552: 1,
 5555: 4,
 5557: 4,
 5559: 2,
 5560: 1,
 5564: 1,
 5565: 1,
 5566: 1,
 5568: 8,
 5578: 2,
 5579: 3,
 5581: 2,
 5582: 1,
 5583: 2,
 5585: 2,
 5588: 1,
 5591: 2,
 5601: 3,
 5611: 2,
 5612: 1,
 5616: 1,
 5622: 1,
 5623: 1,
 5630: 7,
 5635: 1,
 5637: 1,
 5641: 1,
 5647: 2,
 5649: 3,
 5652: 2,
 5656: 2,
 5660: 2,
 5665: 4,
 5666: 2,
 5669: 7,
 5670: 1,
 5671: 1,
 5672: 2,
 5674: 5,
 5677: 2,
 5683: 3,
 5687: 1,
 5692: 1,
 5693: 4,
 5702: 1,
 5709: 1,
 5713: 5,
 5719: 1,
 5721: 1,
 5722: 1,
 5725: 1,
 5726: 1,
 5727: 3,
 5732: 2,
 5736: 3,
 5737: 2,
 5739: 2,
 5740: 3,
 5742: 11,
 5752: 2,
 5753: 1,
 5754: 1,
 5760: 1,
 5772: 10,
 5779: 1,
 5787: 1,
 5790: 1,
 5791: 3,
 5793: 3,
 5794: 1,
 5795: 6,
 5797: 2,
 5802: 2,
 5809: 3,
 5812: 2,
 5814: 1,
 5816: 2,
 5817: 1,
 5819: 7,
 5821: 3,
 5822: 1,
 5825: 1,
 5830: 1,
 5834: 2,
 5842: 1,
 5866: 1,
 5871: 2,
 5882: 1,
 5884: 1,
 5887: 3,
 5889: 3,
 5891: 7,
 5892: 5,
 5894: 1,
 5897: 1,
 5898: 2,
 5900: 6,
 5901: 1,
 5902: 2,
 5903: 2,
 5905: 3,
 5906: 1,
 5909: 1,
 5914: 1,
 5916: 1,
 5917: 3,
 5919: 3,
 5921: 2,
 5922: 2,
 5924: 1,
 5932: 3,
 5936: 1,
 5938: 3,
 5942: 1,
 5943: 1,
 5945: 2,
 5947: 2,
 5954: 2,
 5956: 1,
 5957: 1,
 5970: 1,
 5974: 2,
 5980: 4,
 5987: 3,
 6017: 1,
 6027: 1,
 6028: 1,
 6032: 3,
 6034: 2,
 6035: 2,
 6036: 1,
 6037: 1,
 6038: 1,
 6056: 1,
 6059: 1,
 6062: 1,
 6066: 1,
 6071: 2,
 6077: 1,
 6082: 1,
 6083: 1,
 6085: 1,
 6096: 1,
 6107: 1,
 6108: 1,
 6117: 1,
 6128: 3,
 6145: 1,
 6150: 1,
 6152: 1,
 6156: 1,
 6158: 1,
 6164: 2,
 6184: 3,
 6185: 1,
 6195: 2,
 6212: 1,
 6221: 1,
 6267: 1,
 6271: 3,
 6272: 1,
 6273: 3,
 6284: 1,
 6289: 1,
 6295: 1,
 6296: 2,
 6304: 1,
 6318: 1,
 6323: 1,
 6325: 3,
 6327: 2,
 6331: 1,
 6335: 1,
 6337: 4,
 6338: 1,
 6354: 1,
 6356: 1,
 6360: 2,
 6361: 3,
 6364: 2,
 6365: 5,
 6366: 1,
 6368: 1,
 6372: 1,
 6381: 2,
 6383: 1,
 6388: 2,
 6393: 1,
 6397: 1,
 6400: 2,
 6403: 3,
 6409: 1,
 6411: 2,
 6413: 1,
 6416: 1,
 6425: 2,
 6432: 3,
 6433: 1,
 6434: 2,
 6435: 7,
 6436: 1,
 6437: 1,
 6438: 4,
 6439: 1,
 6440: 2,
 6441: 2,
 6444: 2,
 6445: 3,
 6446: 2,
 6447: 5,
 6449: 3,
 6450: 4,
 6451: 1,
 6452: 3,
 6453: 1,
 6454: 2,
 6465: 1,
 6468: 1,
 6473: 2,
 6475: 4,
 6478: 7,
 6479: 1,
 6480: 2,
 6482: 1,
 6488: 2,
 6492: 1,
 6494: 1,
 6495: 13,
 6497: 1,
 6503: 1,
 6506: 2,
 6508: 2,
 6509: 1,
 6514: 1,
 6522: 2,
 6524: 1,
 6528: 1,
 6530: 1,
 6533: 3,
 6534: 1,
 6535: 2,
 6538: 1,
 6540: 4,
 6541: 5,
 6542: 4,
 6545: 1,
 6546: 1,
 6550: 1,
 6551: 1,
 6553: 1,
 6556: 4,
 6557: 1,
 6561: 4,
 6565: 1,
 6578: 1,
 6592: 1,
 6600: 1,
 6605: 3,
 6614: 3,
 6617: 1,
 6618: 1,
 6626: 1,
 6627: 3,
 6628: 1,
 6630: 1,
 6631: 2,
 6656: 1,
 6666: 1,
 6670: 2,
 6673: 2,
 6719: 1,
 6721: 1,
 6724: 4,
 6736: 1,
 6739: 1,
 6740: 3,
 6753: 2,
 6758: 2,
 6761: 3,
 6768: 1,
 6769: 3,
 6776: 1,
 6779: 1,
 6785: 1,
 6788: 2,
 6789: 1,
 6794: 4,
 6795: 1,
 6799: 1,
 6807: 2,
 6808: 1,
 6812: 4,
 6813: 1,
 6814: 1,
 6817: 1,
 6818: 5,
 6822: 1,
 6823: 3,
 6828: 2,
 6830: 1,
 6832: 2,
 6834: 2,
 6836: 4,
 6839: 1,
 6840: 1,
 6843: 2,
 6847: 1,
 6884: 1,
 6890: 1,
 6895: 1,
 6905: 1,
 6909: 4,
 6920: 1,
 6957: 1,
 6964: 1,
 6971: 2,
 6974: 3,
 6976: 1,
 6989: 3,
 7000: 1,
 7012: 2,
 7039: 2,
 7050: 1,
 7051: 4,
 7052: 1,
 7053: 1,
 7071: 1,
 7107: 2,
 7108: 3,
 7109: 1,
 7111: 3,
 7114: 4,
 7117: 1,
 7118: 1,
 7119: 1,
 7121: 1,
 7122: 3,
 7125: 3,
 7126: 2,
 7127: 4,
 7128: 6,
 7129: 2,
 7130: 1,
 7131: 2,
 7137: 2,
 7146: 1,
 7150: 1,
 7153: 3,
 7156: 2,
 7170: 2,
 7174: 1,
 7188: 1,
 7192: 5,
 7202: 1,
 7207: 1,
 7211: 1,
 7212: 1,
 7216: 1,
 7223: 1,
 7236: 3,
 7254: 1,
 7287: 1,
 7291: 1,
 7292: 1,
 7294: 1,
 7314: 1,
 7319: 3,
 7336: 1,
 7349: 1,
 7350: 1,
 7361: 2,
 7367: 1,
 7368: 1,
 7370: 2,
 7382: 1,
 7383: 1,
 7390: 1,
 7433: 3,
 7449: 3,
 7450: 2,
 7451: 1,
 7452: 8,
 7454: 1,
 7457: 2,
 7461: 1,
 7462: 2,
 7463: 2,
 7465: 1,
 7466: 1,
 7467: 2,
 7469: 2,
 7470: 2,
 7473: 1,
 7474: 2,
 7486: 2,
 7490: 2,
 7493: 2,
 7496: 5,
 7499: 3,
 7500: 1,
 7538: 3,
 7540: 1,
 7544: 1,
 7548: 1,
 7550: 2,
 7555: 1,
 7572: 1,
 7627: 1,
 7649: 2,
 7658: 1,
 7727: 1,
 7748: 1,
 7775: 2,
 7779: 1,
 7831: 2,
 7860: 3,
 7864: 1,
 7889: 1,
 7894: 1,
 7898: 1,
 7899: 1,
 7900: 1,
 7904: 1,
 7909: 2,
 7912: 5,
 7913: 3,
 7917: 3,
 7919: 1,
 7931: 1,
 7934: 1,
 7938: 1,
 7945: 1,
 7948: 1,
 7957: 1,
 7961: 2,
 7963: 4,
 7966: 1,
 7983: 4,
 7990: 4,
 7993: 14,
 7994: 2,
 8002: 3,
 8009: 1,
 8010: 1,
 8012: 1,
 8019: 1,
 8020: 1,
 8024: 1,
 8038: 2,
 8045: 2,
 8048: 1,
 8049: 1,
 8056: 1,
 8060: 3,
 8068: 3,
 8071: 1,
 8072: 3,
 8073: 2,
 8075: 1,
 8079: 2,
 8080: 1,
 8085: 1,
 8090: 1,
 8092: 1,
 8093: 2,
 8105: 1,
 8107: 1,
 8108: 2,
 8109: 3,
 8118: 2,
 8121: 1,
 8125: 4,
 8127: 1,
 8128: 2,
 8131: 1,
 8132: 5,
 8134: 1,
 8138: 1,
 8139: 1,
 8148: 2,
 8151: 3,
 8166: 1,
 8171: 1,
 8178: 4,
 8180: 1,
 8183: 3,
 8193: 1,
 8194: 2,
 8197: 4,
 8198: 3,
 8199: 8,
 8200: 1,
 8201: 2,
 8203: 4,
 8205: 1,
 8210: 1,
 8211: 2,
 8213: 1,
 8215: 1,
 8219: 1,
 8229: 2,
 8230: 1,
 8236: 1,
 8237: 1,
 8241: 1,
 8243: 5,
 8244: 10,
 8249: 4,
 8250: 1,
 8251: 3,
 8252: 1,
 8253: 1,
 8254: 5,
 8255: 3,
 8257: 1,
 8260: 2,
 8263: 1,
 8264: 2,
 8265: 1,
 8266: 4,
 8268: 5,
 8270: 1,
 8271: 1,
 8272: 2,
 8275: 1,
 8279: 1,
 8284: 2,
 8285: 5,
 8287: 1,
 8290: 11,
 8293: 6,
 8310: 4,
 8317: 2,
 8320: 1,
 8321: 3,
 8322: 1,
 8326: 1,
 8327: 2,
 8338: 1,
 8339: 4,
 8346: 1,
 8349: 1,
 8353: 1,
 8370: 1,
 8402: 2,
 8411: 1,
 8433: 1,
 8434: 2,
 8445: 2,
 8451: 1,
 8459: 1,
 8465: 1,
 8467: 1,
 8468: 5,
 8488: 1,
 8500: 1,
 8501: 1,
 8504: 3,
 8506: 2,
 8508: 1,
 8517: 4,
 8518: 4,
 8520: 1,
 8529: 2,
 8543: 3,
 8544: 1,
 8545: 1,
 8547: 2,
 8549: 1,
 8551: 13,
 8555: 5,
 8557: 2,
 8558: 2,
 8559: 1,
 8561: 26,
 8562: 2,
 8563: 4,
 8564: 22,
 8567: 3,
 8568: 5,
 8569: 9,
 8571: 1,
 8572: 1,
 8573: 11,
 8577: 10,
 8578: 6,
 8582: 1,
 8586: 27,
 8588: 26,
 8589: 35,
 8590: 8,
 8591: 9,
 8593: 2,
 8595: 16,
 8596: 1,
 8597: 3,
 8599: 10,
 8602: 12,
 8608: 4,
 8613: 5,
 8614: 2,
 8616: 2,
 8618: 17,
 8619: 3,
 8620: 5,
 8621: 45,
 8624: 2,
 8626: 1,
 8628: 1,
 8631: 1,
 8633: 3,
 8636: 1,
 8640: 17,
 8642: 2,
 8646: 2,
 8648: 1,
 8650: 7,
 8652: 4,
 8653: 6,
 8665: 4,
 8669: 2,
 8672: 2,
 8676: 2,
 8682: 4,
 8686: 5,
 8688: 4,
 8691: 3,
 8692: 2,
 8696: 1,
 8697: 1,
 8700: 2,
 8708: 4,
 8709: 2,
 8711: 1,
 8716: 4,
 8720: 3,
 8722: 1,
 8724: 2,
 8730: 2,
 8732: 1,
 8733: 4,
 8738: 2,
 8742: 4,
 8744: 19,
 8747: 1,
 8749: 1,
 8750: 1,
 8751: 1,
 8756: 2,
 8757: 1,
 8758: 1,
 8763: 1,
 8766: 4,
 8769: 2,
 8772: 9,
 8773: 1,
 8781: 1,
 8782: 1,
 8783: 1,
 8786: 2,
 8788: 6,
 8796: 44,
 8801: 2,
 8806: 1,
 8809: 8,
 8810: 3,
 8811: 1,
 8813: 4,
 8814: 1,
 8815: 1,
 8816: 4,
 8818: 9,
 8822: 1,
 8825: 4,
 8830: 12,
 8836: 5,
 8837: 2,
 8838: 1,
 8845: 1,
 8846: 2,
 8852: 1,
 8857: 1,
 8860: 2,
 8862: 1,
 8873: 1,
 8876: 1,
 8877: 1,
 8884: 1,
 8885: 1,
 8888: 1,
 8891: 2,
 8892: 3,
 8894: 1,
 8896: 2,
 8897: 3,
 8898: 2,
 8899: 1,
 8900: 2,
 8903: 1,
 8906: 1,
 8916: 6,
 8918: 1,
 8921: 2,
 8922: 1,
 8925: 3,
 8926: 2,
 8928: 4,
 8929: 1,
 8932: 1,
 8937: 2,
 8938: 1,
 8947: 2,
 8948: 2,
 8956: 1,
 8957: 1,
 8958: 4,
 8961: 2,
 9029: 8,
 9052: 1,
 9071: 1,
 9077: 1,
 9120: 1,
 9122: 1,
 9133: 1,
 9134: 1,
 9135: 2,
 9138: 2,
 9139: 2,
 9140: 1,
 9157: 1,
 9165: 1,
 9167: 3,
 9168: 2,
 9171: 3,
 9184: 2,
 9192: 1,
 9198: 1,
 9208: 1,
 9209: 1,
 9221: 6,
 9230: 5,
 9231: 1,
 9233: 5,
 9236: 1,
 9237: 1,
 9238: 1,
 9242: 1,
 9243: 4,
 9246: 1,
 9247: 4,
 9248: 3,
 9257: 2,
 9268: 1,
 9272: 1,
 9275: 1,
 9282: 1,
 9283: 3,
 9284: 1,
 9289: 1,
 9294: 1,
 9303: 1,
 9310: 1,
 9324: 1,
 9332: 1,
 9337: 1,
 9340: 7,
 9341: 1,
 9350: 7,
 9352: 2,
 9356: 1,
 9358: 2,
 9361: 2,
 9362: 1,
 9367: 2,
 9370: 2,
 9373: 1,
 9376: 1,
 9379: 1,
 9381: 1,
 9382: 1,
 9384: 1,
 9390: 1,
 9391: 3,
 9394: 1,
 9398: 2,
 9399: 4,
 9414: 1,
 9419: 1,
 9420: 2,
 9423: 1,
 9425: 1,
 9426: 4,
 9432: 1,
 9442: 2,
 9461: 1,
 9486: 1,
 9513: 1,
 9538: 2,
 9539: 1,
 9541: 1,
 9567: 2,
 9579: 1,
 9582: 2,
 9597: 1,
 9612: 1,
 9663: 1,
 9709: 2,
 9710: 1,
 9720: 1,
 9729: 1,
 9748: 1,
 9749: 1,
 9773: 1,
 9779: 2,
 9780: 1,
 9782: 1,
 9793: 1,
 9826: 3,
 9840: 1,
 9853: 1,
 9860: 2,
 9862: 2,
 9863: 1,
 9864: 4,
 11316: 8,
 11321: 2,
 11322: 1,
 11325: 1,
 11329: 1,
 11333: 1,
 11393: 2,
 11397: 1,
 11398: 1,
 11410: 2,
 11412: 1,
 11451: 2,
 11454: 1,
 11458: 1,
 11484: 1,
 11496: 1,
 11498: 2,
 11500: 2,
 11508: 1,
 11532: 1,
 11534: 1,
 11541: 2,
 11546: 1,
 11547: 1,
 11553: 1,
 11554: 1,
 11566: 2,
 11571: 2,
 11575: 1,
 11579: 1,
 11695: 3,
 11697: 1,
 11713: 1,
 11771: 2,
 11786: 1,
 11795: 1,
 11800: 1,
 11810: 1,
 11812: 1,
 11815: 1,
 11819: 1,
 11820: 3,
 11849: 1,
 11853: 1,
 11859: 1,
 11892: 2,
 11898: 1,
 11902: 1,
 11910: 2,
 11912: 1,
 11913: 1,
 11914: 2,
 11918: 1,
 11926: 1,
 11936: 1,
 11937: 2,
 11938: 1,
 11939: 2,
 11945: 3,
 11952: 2,
 11956: 2,
 11957: 1,
 11960: 4,
 11975: 2,
 11980: 3,
 11983: 1,
 11984: 3,
 11993: 1,
 11996: 1,
 11998: 1,
 12001: 1,
 12003: 7,
 12007: 2,
 12010: 1,
 12012: 1,
 ...}

In [11]:
# count the numeric references (skipping NaN in the test)
res_df = df[(df.action_type == 'clickout item') & (df.reference.str.isnumeric() == True)]
res_df = res_df[['reference','frequence']].astype('int').groupby('reference').sum()
res_df['frequence'] -= 1
res_df = res_df[res_df['frequence'] > 0]

In [12]:
res_df

           frequence
reference
5001               3
5002               7
5003               6
5004               9
5006               1
5009               4
5013               2
5014              32
5015              16
5016              10
5017              29
5019               4
5020              14
5021              18
5022               7
5023              24
5027               2
5029               2
5036               6
5037               5
5040               6
5041              25
5042              20
5043               4
5046               8
5048               1
5049              17
5050              22
5051               8
5052              31
...              ...
11230218           1
11231346          10
11232140          11
11233346           2
11234060           3
11234066           4
11236204           1
11239084           1
11239530           3
11239870           1
11240344           6
11241060           2
11241252           1
11243330           1
11243970           1
11246040           1
11249888           1
11254538           1
11256320           1
11257928           2
11259944           8
11262114           3
11264090           1
11265108           1
11265456           2
11268328           1
11268332           3
11272358           1
11274270           4
11274320           3

[188640 rows x 1 columns]

In [13]:
min_pop = res_df['frequence'].values.min()
max_pop = res_df['frequence'].values.max()
min_pop, max_pop

(1, 935)

In [14]:
min_pop = np.log(min_pop)
max_pop = np.log(max_pop)

In [16]:
res_df['frequence'] = (np.log(res_df['frequence'].values) - min_pop) / (max_pop - min_pop)

In [17]:
res_df

           frequence
reference
5001        0.160603
5002        0.284467
5003        0.261932
5004        0.321206
5006        0.000000
5009        0.202658
5013        0.101329
5014        0.506646
5015        0.405317
5016        0.336608
5017        0.492255
5019        0.202658
5020        0.385796
5021        0.422535
5022        0.284467
5023        0.464591
5027        0.101329
5029        0.101329
5036        0.261932
5037        0.235279
5040        0.261932
5041        0.470558
5042        0.437938
5043        0.202658
5046        0.303988
5048        0.000000
5049        0.414179
5050        0.451871
5051        0.303988
5052        0.502005
...              ...
11230218    0.000000
11231346    0.336608
11232140    0.350541
11233346    0.101329
11234060    0.160603
11234066    0.202658
11236204    0.000000
11239084    0.000000
11239530    0.160603
11239870    0.000000
11240344    0.261932
11241060    0.101329
11241252    0.000000
11243330    0.000000
11243970    0.000000
11246040    0.000000
11249888    0.000000
11254538    0.000000
11256320    0.000000
11257928    0.101329
11259944    0.303988
11262114    0.160603
11264090    0.000000
11265108    0.000000
11265456    0.101329
11268328    0.000000
11268332    0.160603
11272358    0.000000
11274270    0.202658
11274320    0.160603

[188640 rows x 1 columns]

In [23]:
def impressions_pop(df):
    cnt = Counter(df[(df.action_type == 'clickout item') & (df.reference.str.isnumeric() == True)].reference.values.astype(int))
        
    # find the clickout rows
    clickout_rows = df[df.action_type == 'clickout item'][['reference','impressions']]
    clickout_rows = clickout_rows.fillna(-1).astype({'reference':'int'})
    clickout_rows['impressions'] = clickout_rows.apply(lambda x: list(map(int,x.impressions.split('|'))), axis=1)

    # build the resulting matrix
    matrix = np.zeros((clickout_rows.shape[0],25), dtype=int)

    i = 0
    for impr in tqdm(clickout_rows.impressions):
        for j,impr in enumerate(impr):
            ## OLD version
            #popularity = cnt[impr] if impr in cnt else 0
            #if popularity == row.reference:
            #    popularity -= 1

            ## NEW ! (decrease 1 to all references)
            popularity = cnt[impr]-1 if impr in cnt else 0
            matrix[i, j] = popularity
        i += 1
    
    return matrix

In [24]:
m = impressions_pop(df)

HBox(children=(IntProgress(value=0, max=2115364), HTML(value='')))

## Test

In [3]:
from extract_features.global_popularity import GlobalPopularity
ref_glob_popul = GlobalPopularity('small', 'cluster_recurrent')

In [4]:
ref_glob_popul.read_feature()
#ref_glob_popul.save_feature()

global_popularity feature read

        reference  glob_popularity
0            5001               24
1            5002               45
2            5003              104
3            5004               32
4            5005                6
5            5006               24
6            5007               31
7            5009               34
8            5011               31
9            5013               24
10           5014              301
11           5015              112
12           5016              291
13           5017              127
14           5019               26
15           5020              101
16           5021              290
17           5022              294
18           5023              162
19           5027               13
20           5029               40
21           5033               26
22           5035                1
23           5036               34
24           5037               57
25           5040               26
26           5041              148
27           5042              107
28           5043                6
29           5046               27
...           ...              ...
297454   11239530                2
297455   11239814                2
297456   11240344                1
297457   11241252                1
297458   11245240                1
297459   11245560                1
297460   11246550                1
297461   11248816               14
297462   11249570                1
297463   11249848                1
297464   11249902                1
297465   11250428               12
297466   11251774                1
297467   11252674                1
297468   11255022                1
297469   11255326                1
297470   11255992                2
297471   11256300                1
297472   11258716                5
297473   11259004                1
297474   11259730                1
297475   11260166                1
297476   11264560                1
297477   11265454                3
297478   11265456                1
297479   11266490                1
297480   11266818                1
297481   11267658                1
297482   11268332                1
297483   11274320                1

[297484 rows x 2 columns]

In [4]:
ref_glob_popul.join_to(data.train_df('small'))

global_popularity feature read

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,frequence,glob_popularity
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,0,0,0,1,0
1,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,3,76
2,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,1,297
3,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,1,76
4,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,1,297
5,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,1,76
6,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,5,297
7,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,0,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,1,0
8,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,0,0,0,1,0
9,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,0,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1,0
10,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,1,614
11,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,2,614
12,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,1,614
13,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,1,231
14,02HGRBA06ODU,fa3a53156ae5c,1541030978,28,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,23,231
15,02HGRBA06ODU,fa3a53156ae5c,1541031009,29,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,1,231
16,02HGRBA06ODU,fa3a53156ae5c,1541031044,46,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,17,231
17,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,1,231
18,02HGRBA06ODU,fa3a53156ae5c,1541031115,65,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,18,231
19,02SRUT1NQYH1,3599a6f709eab,1541063851,33,interaction item image,2795374,FI,"Krakow, Poland",mobile,0,0,0,33,502
20,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,0,0,0,1,502
21,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,0,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...,1,0
22,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,0,0,0,1,0
23,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,0,0,0,1,0
24,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,0,0,0,1,0
25,03K8AXBL4BX2,ec139e10b9238,1541100314,5,interaction item image,1032816,UK,"London, United Kingdom",desktop,0,0,0,2,34
26,03K8AXBL4BX2,ec139e10b9238,1541100652,7,clickout item,1032816,UK,"London, United Kingdom",desktop,0,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...,2,0
27,03P4VFKK12UO,325fafb5fa450,1541107286,2,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,0,0,0,2,0
28,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,0,0,1,0
29,03P4VFKK12UO,325fafb5fa450,1541107366,4,filter selection,Hostal (ES),US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79551,X5LCV1SW6B0G,6288f0e7db512,1541405514,27,clickout item,Hotel,PL,"Bukowina Tatrzanska, Poland",desktop,0,988737|3936874|2673738|4779488|3557634|5540134...,23|27|27|19|23|32|63|75|18|84|25|25|23|16|28|2...,1,0
79552,X5RBR58Z3M62,21ffead5b9c92,1541417747,1,search for destination,Free WiFi (Combined),UK,"Liverpool, United Kingdom",desktop,0,0,0,1,0
79553,X5RBR58Z3M62,21ffead5b9c92,1541417941,10,interaction item image,Air Conditioning,UK,"Liverpool, United Kingdom",desktop,0,0,0,9,582
79554,X5RBR58Z3M62,21ffead5b9c92,1541418014,43,interaction item image,Swimming Pool (Combined Filter),UK,"Liverpool, United Kingdom",desktop,0,0,0,33,340
79555,X5RBR58Z3M62,21ffead5b9c92,1541418089,74,interaction item image,5106514,UK,"Liverpool, United Kingdom",desktop,0,0,0,31,819
79556,X5RBR58Z3M62,21ffead5b9c92,1541418089,75,interaction item info,Breakfast Included,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,819
79557,X5RBR58Z3M62,21ffead5b9c92,1541418144,76,clickout item,1205154,UK,"Liverpool, United Kingdom",desktop,0,152875|47374|2707162|18904|2826684|706646|9332...,185|69|102|109|284|192|129|180|170|77|92|134|1...,1,0
79558,X5RBR58Z3M62,21ffead5b9c92,1541418502,99,interaction item image,Hotel,UK,"Liverpool, United Kingdom",desktop,0,0,0,23,420
79559,X5RBR58Z3M62,21ffead5b9c92,1541418502,100,interaction item image,Resort,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,340
79560,X5RBR58Z3M62,21ffead5b9c92,1541418504,101,interaction item image,5 Star,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,420
79561,X5RBR58Z3M62,21ffead5b9c92,1541418537,115,interaction item image,Free WiFi (Combined),UK,"Liverpool, United Kingdom",desktop,0,0,0,14,819
79562,X5RBR58Z3M62,21ffead5b9c92,1541418537,117,interaction item image,Air Conditioning,UK,"Liverpool, United Kingdom",desktop,0,0,0,2,933
79563,X5RBR58Z3M62,21ffead5b9c92,1541418537,121,interaction item image,Swimming Pool (Combined Filter),UK,"Liverpool, United Kingdom",desktop,0,0,0,4,819
79564,X5RBR58Z3M62,21ffead5b9c92,1541418547,135,interaction item image,Hotel,UK,"Liverpool, United Kingdom",desktop,0,0,0,14,933
79565,X5RBR58Z3M62,21ffead5b9c92,1541418555,136,clickout item,Resort,UK,"Liverpool, United Kingdom",desktop,0,2530750|2707162|706646|18904|12618|3842698|470...,38|68|92|69|81|79|57|100|90|103|74|46|69|78|66...,1,0
79566,X5RBR58Z3M62,21ffead5b9c92,1541418612,137,interaction item image,5 Star,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,819
79567,X5RBR58Z3M62,21ffead5b9c92,1541418614,138,interaction item image,Free WiFi (Combined),UK,"Liverpool, United Kingdom",desktop,0,0,0,1,420
79568,X5RBR58Z3M62,21ffead5b9c92,1541418614,139,interaction item image,Air Conditioning,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,340
79569,X5RBR58Z3M62,21ffead5b9c92,1541418614,140,interaction item image,Breakfast Included,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,582
79570,X5RBR58Z3M62,21ffead5b9c92,1541418614,141,interaction item image,interaction sort button,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,819
79571,X5RBR58Z3M62,21ffead5b9c92,1541418615,142,interaction item image,Hotel,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,420
79572,X5RBR58Z3M62,21ffead5b9c92,1541418615,143,interaction item image,Resort,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,819
79573,X5RBR58Z3M62,21ffead5b9c92,1541418615,144,interaction item image,5 Star,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,582
79574,X5RBR58Z3M62,21ffead5b9c92,1541418620,145,interaction item image,Breakfast Included,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,819
79575,X5RBR58Z3M62,21ffead5b9c92,1541418634,146,interaction item image,3556430,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,340
79576,X5RBR58Z3M62,21ffead5b9c92,1541418634,147,interaction item image,3556430,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,420
79577,X5RBR58Z3M62,21ffead5b9c92,1541418634,148,interaction item image,5 Star,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,582
79578,X5RBR58Z3M62,21ffead5b9c92,1541418732,161,interaction item image,Hotel,UK,"Liverpool, United Kingdom",desktop,0,0,0,13,340
79579,X5RBR58Z3M62,21ffead5b9c92,1541418745,162,clickout item,Resort,UK,"Liverpool, United Kingdom",desktop,0,18910|743096|47374|2826684|1364710|5206872|132...,200|86|101|284|102|106|413|166|184|164|133|200...,1,0
79580,X5RBR58Z3M62,21ffead5b9c92,1541418767,163,interaction item deals,5 Star,UK,"Liverpool, United Kingdom",desktop,0,0,0,1,29